### ISSUE TITLE
Don't put headings inside labels

### ISSUE THREAD

**Issue by oliverjam** [fac22/week2-MCD-eBargain#33]
https://github.com/fac22/week2-MCD-eBargain/blob/c2d7acf900687d21f85ebe9bdb0705ecdf303ce4/routes/html.js#L25-L26

Putting headings (like `h2`s) inside `label`s  can be bad for accessibility. Headings are supposed to mark the start of a new section (and allow users to scan/jump to it), whereas labels describe what a single input does. It doesn't really make sense to have one element do both things. More info: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#headings

It's fine to style a label to look bigger/bolder if you want, without using a heading.

**Comment by cem-al** [comment]
Thank you! Really helpful as usual
