### ISSUE TITLE
Using fonts

### ISSUE THREAD

**Issue by oliverjam** [fac22/week2-MCD-eBargain#34]
https://github.com/fac22/week2-MCD-eBargain/blob/c2d7acf900687d21f85ebe9bdb0705ecdf303ce4/public/style.css#L17-L22

You're loading the Fira Code font in your CSS, but then never actually using it for any element. Fonts can be quite big so I'd recommend not loading them if you're not using them, as it'll slow down the page.

Also `font-family` is an _inherited_ CSS property—this means it's generally easier to set it once at the "top-level" of the document and let all the children inherit it. E.g. you've specified `font-family: 'Arial'` 7 times. You should be able to set this once on the `body`.

The only downside is that certain form elements _don't_ inherit font stuff by default (so e.g. `textarea`s and `button`s would not use the font you specified. You can fix this with `font-family: inherit`—that way you don't have to repeat yourself so much (and remember to change it in all those places when you want to change the font).

Also it's always a good idea to specify a guaranteed fallback font family (like `sans-serif`) in case the font you ask for doesn't exist on the user's computer. Otherwise you're likely to end up with something like Times New Roman, which looks very different to Arial.

**Comment by cem-al** [comment]
Thank you @oliverjam really appreciate this explination, makes alot of sense! 

We've made the changes you've suggested.
