### ISSUE TITLE
When committing add individual files

### ISSUE THREAD

**Issue by jijip41** [fac22/week2-MCD-eBargain#42]
So that commit messages refer to the files only

**Comment by Moggach** [comment]
![Screenshot 2021-10-08 at 10 18 02](https://user-images.githubusercontent.com/43313455/136531381-1ef1555f-41e5-4c89-8b76-7eced8dfbde7.png)

Commit message associated with database files but referring to CSS changes
Better to add individual files rather than git add .

**Comment by cem-al** [comment]
Thank you!
